/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learning.language;

import learning.language.dao.Person;
import lombok.extern.java.Log;

@Log
public class App {
    public String getGreeting() {
        Person person = new Person();
        person.setName("Praveen");
        person.setAge(42);
        person.setSex(Person.Sex.MALE);
        person.setEmailId("praveen.chappidi@gmail.com");
        log.info("Person created with lombok:"+person);
        return "Hello world.";
    }

    public static void main(String[] args) {
        log.info(new App().getGreeting());
    }
}
